### PR TITLE
Log the reason an error occurred.

### PR DESCRIPTION
**Pull request by Peter-Barrett**
This is a straightforward PR, I just wanted more info on why an error was occurring.

### CODE REVIEW

**Comment by Peter-Barrett** [comment]
@shaharke are you maintaining this?

**Comment by shaharke** [comment]
Unfortunately I don't have much time to really maintain it. I get to merge
PRs only once every few months. Any volunteers?

**Comment by Peter-Barrett** [comment]
I'm more than happy to look over and merge PR's anyway, it's a module I use pretty frequently.

**Comment by shaharke** [comment]
@Peter-Barrett since I don't own this repo I can't really add you as contributor. @guzru can you add him?

**Comment by Peter-Barrett** [comment]
No problem, let me know @guzru, cheers.

**Comment by guzru** [comment]
Done! Sorry for the wait :)

**Comment by Peter-Barrett** [comment]
No problem at all, should I bump the version to 0.1.2 for this?

**Pull request merged**
