### PR TITLE
Add support for custom logging levels

### LINKED ISSUE #26: Support custom logging levels
We are currently using custom logging levels and would like to set our own levels map.

### PR DESCRIPTION
**Pull request by zimlin**
Resolves #26

### CODE REVIEW

**Comment by Peter-Barrett** [comment]
Will you have a quick look at this PR https://github.com/guzru/winston-sentry/pull/25/files and set `this._levels_map = options.levels_map` above delete options, then delete it from options before they're passed to sentry? Looks good though 👍

**Comment by shaharke** [comment]
@adambiggs I think we can close this now right?

**Comment by adambiggs** [comment]
Yes, this is now possible using the `levelsMap` option.

**Comment by shaharke** [comment]
This is resolved by #30

**Pull request closed without merging**
